### PR TITLE
Switched to xdg-base-dir location for config

### PR DESCRIPTION
**Pull request by draxaris1010**
# Merging into master
This document serves as a checklist before merging a pull request into master. This is in place because this merge
will automatically trigger a new package release. Releases require some thought after all.

## Checklist before merging 
- [x] (N/A) Documentation updated
- [x] Config.json changes reflected in **source**/get_data.validate_config
- [x] Version number updated in pyproject.toml
- [x] (N/A) Completion script updated

---
For linux there is a standard defined by freedesktop.org called [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
It defines where a program should look for configuration and data.

Below is a summary on where a program should look written in bash syntax. (look for `${parameter:-word}` in the manpage)
|                            | Configuration                                             | Data (eg. icons, themes, .desktop files)                  |
|-------------------|-----------------------------------------------|-------------------------------------------------------|
| User                    | `${XDG_CONFIG_HOME:-$HOME/.config}` | `${XDG_DATA_HOME:-$HOME/.local/share}`         |
| System(defaults) | `${XDG_CONFIG_DIRS:-/etc/xdg}`               | `${XDG_DATA_DIRS:-/usr/local/share:/usr/share}` |

I've implemented this in the pull request, the only thing that is needed is a migration from the old location.

### CODE REVIEW

**Comment by BWindey** [comment]
I moved the base branch to develop as I'd like to add this change to master together with an "update" subcommand. That should handle the migration as well.

My only problem with this change, is that I don't know how it will work on MacOS. I would like to support that platform as well, as I already know of a person who uses DodonaCLI on a Mac.

**Comment by BWindey** [comment]
I heard from some Apple users that they would like to have the same system as you proposed already in this PR. So if you want you can unmark this as a draft PR and merge, or you can write a migration function if you'd like.

**Comment by draxaris1010** [comment]
I have added the migration and also some directories for common platforms.
Also before merging: I've just found out that the case syntax is only available from python >= 3.10

**Comment by draxaris1010** [comment]
> Also before merging: I've just found out that the case syntax is only available from python >= 3.10

I've fixed this issue.

**Comment by BWindey** [comment]
Thanks a lot for your contribution! I'll put some more work in DodonaCLI the coming weeks, and your changes will be in the next release.

**Pull request merged**
